import type { Metadata } from 'next'
import { Noto_Sans_JP } from 'next/font/google'
import Script from 'next/script'
import { Analytics } from '@vercel/analytics/react'
import { SpeedInsights } from '@vercel/speed-insights/next'

import { metadataConfig } from '@/config/metadata'
import { cn } from '@/lib/utils'
import { Toaster } from '@/components/ui/toaster'
import { Providers } from '@/components/providers'

import '@/styles/globals.css'

export const fontSans = Noto_Sans_JP({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = metadataConfig

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <!-- JSON-LD markup generated by Google Structured Data Markup Helper. --> */}
      <Script
        id="schema.org"
        type="application/ld+json"
        strategy="beforeInteractive"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'http://schema.org',
            '@type': 'Product',
            name: 'Collaborate Seamlessly with Revent',
            image: [
              'https://www.reventapp.com/_next/image?url=%2Fimages%2Fproject-app-screenshot-black.png&w=3840&q=75',
              'https://www.reventapp.com/_next/image?url=%2Fimages%2Fproject-app-screenshot.png&w=3840&q=75',
            ],
            description:
              'Our platform ensures secure, scalable event workflows, with seamless promotion and efficient project management for easy organizing.',
            url: 'https://reventapp.com/sign-in',
            brand: [
              {
                '@type': 'Brand',
                logo: 'https://www.reventapp.com/',
              },
              {
                '@type': 'Brand',
                logo: 'https://www.reventapp.com/images/logo-white.svg',
              },
            ],
            offers: {
              '@type': 'Offer',
              price: '$49/month',
            },
          }),
        }}
      />
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <Providers>
          {children}
          <Toaster />
          <Analytics />
          <SpeedInsights />
        </Providers>
      </body>
    </html>
  )
}
