import type { Metadata } from 'next'
import { Noto_Sans_JP } from 'next/font/google'
import Script from 'next/script'
import { GoogleTagManager } from '@next/third-parties/google'
import { Analytics } from '@vercel/analytics/react'
import { SpeedInsights } from '@vercel/speed-insights/next'

import { jsonLd, metadataConfig } from '@/config/metadata'
import { cn } from '@/lib/utils'
import { Toaster } from '@/components/ui/toaster'
import { Providers } from '@/components/providers'

import '@/styles/globals.css'

import { env } from '@/env.mjs'

export const fontSans = Noto_Sans_JP({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = metadataConfig

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <!-- JSON-LD markup generated by Google Structured Data Markup Helper. --> */}
      <Script
        id="schema.org"
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(jsonLd),
        }}
      />
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <Providers>
          {children}
          <Toaster />
          <Analytics />
          <SpeedInsights />
        </Providers>
        <GoogleTagManager gtmId={env.GOOGLE_TAG_MANAGER_ID} />
      </body>
    </html>
  )
}
