name: Jest Tests and Linting
on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn install --immutable
      - name: Next Linting
        run: yarn lint
      - name: Run tests
        run: yarn test
